services:
  backend:
    build: ./backend
    ports:
      - "5051:5051"
    networks:
      - mern_network

  frontend:
    build: ./frontend
    ports:
      - "5176:5176"
    networks:
      - mern_network
    environment:
      - VITE_REACT_APP_API_URL=http://backend:5051/api/todos

networks:
  mern_network:
    driver: bridge
